apiVersion: v1
kind: Service
metadata:
  name: grepjava
  labels:
    app: grepjava
spec:
  ports:
    - port: 80
  selector:
    app: grepjava
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grepjava
  labels:
    app: grepjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grepjava
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grepjava
        tier: frontend
    spec:
      containers:
      - image: 77ruthvik/grep:latest
        args: [".*Romeo.*Juliet.*", "/data", "/log/grep.out"]
        name: grepjava
        volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: log-volume
            mountPath: /log
        lifecycle:
          postStart:
            exec:
              command: ["echo", "task started"]
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: log-volume
        emptyDir: {}
